gc: Autospec creation for update from version 8.0.4 to version 8.0.6
Alaskan Emily (1):
      Fix compiling by Makefile.direct on OpenBSD/UltraSparc

Christian Weisgerber (1):
      Add support of OpenBSD/aarch64

Clement Chigot (1):
      Include <alloca.h> when using alloca on AIX

Dima Pasechnik (1):
      Fix 'traceable but uncollectible memory' wording in gcinterface document

Ivan Maidanski (166):
      Update AUTHORS file (add Richard Zidlicky)
      Update AUTHORS file (add Peter Budai)
      Support MSYS builds by CMake
      Update copyright information (year) in alloc.c and README.QUICK
      Update AUTHORS file (add Alaskan Emily)
      Fix various typos mostly in documentation files
      Refine GC_INIT documentation about its multiple invocation
      Fix configure message about 'AIX gcc optimization fix'
      Fix incorrect markup formatting in documentation
      windows-untested: Update after include/gc_inl.h removal
      Fix printf format specifier in simple_example.md
      Update ChangeLog file (v7.2 - v7.4 changes only)
      Update ChangeLog file (v7.6 changes)
      Update ChangeLog file (v8.0 changes)
      Avoid compiler warning about unused d in GC_CALLOC/MALLOC_EXPLICITLY_TYPED
      Fix OS_TYPE and USE_MMAP_ANON definitions for Cygwin/x64
      Remove a misleading comment about Solaris in gc.h
      Fix a typo (GC_NPROCS spelling) in a comment in gc.h
      Refine GC_parallel documentation in gc.h
      Update documentation about the incremental collector support
      Fix typos in documentation (regarding 'non-incremental')
      Update ChangeLog file (v7.2 - v7.4 changes only)
      Update ChangeLog file (v7.6 changes)
      Update ChangeLog file (v8.0 changes)
      Enable sbrk-to-mmap fallback on major supported Unix-like platforms
      Travis CI: Add a test of configure --enable-mmap (Linux)
      Fix MPROTECT_VDB definition for single-threaded GC builds
      Fix save_callers for multi-threaded case if built-in backtrace unavailable
      Explicitly zero-initialize trace_buf
      Refine do_blocking() documentation in gc.h
      Fix the stack bottom variable name in README
      Fix first_thread stack_base initialzation if custom GC_stackbottom (Win32)
      Update AUTHORS file (add Christian Weisgerber)
      Allow GC_PAUSE_TIME_TARGET environment variable values smaller than 5 ms
      Update AUTHORS file (add Jasper Lievisse Adriaanse)
      Update ChangeLog file (v7.2 - v7.4 changes only)
      Update ChangeLog file (v7.6 changes)
      Update ChangeLog file (v8.0 changes)
      Travis CI: Fix out-of-memory during cppcheck build
      Travis CI: Replace clang-5.0 with clang (update to Xenial image)
      Do not use Manual VDB mode if C malloc is redirected
      .gitignore: Ignore various CMake-generated files
      Fix 'unused function GC_add_map_entry' compiler warning
      Update AUTHORS file (add Victor Romero)
      Fix 'while clause does not guard' GCC warning in GC_parse_map_entry
      Fix 'unused function GC_lock' compiler warning
      Fix 'GC_old_bus_handler defined but not used' compiler warning
      Fix fread failure after enable_incremental if malloc is redirected (Linux)
      Update AUTHORS file (add iarspider)
      Fix building of shared library with C++ support on MinGW
      Fix 'external linkage required for var because of dllimport' error on MinGW
      Remove gcmt-lib generation by CMake
      Appveyor CI: Pass CMAKE_OPTIONS to cmake only when configuring
      AppVeyor CI: Add CMake build with the default release configuration
      Update ChangeLog file (v7.2 - v7.4 changes only)
      Update ChangeLog file (v7.6 changes)
      Update ChangeLog file (v8.0 changes)
      .gitignore: Ignore de.dir produced by CMake
      .gitignore: Ignore all *.a files in the base folder
      Fix cordtest build in SMakefile.amiga
      Fix test_cpp fail when gc_cpp resides in a dll (Borland, Watcom)
      Fix typo in SMakefile filename in README
      Fix a typo in control_chars() comment in de_win.c
      Fix test_cpp failure caused by arbitrary link order (Win32)
      Fix 'wrong finalization data' gctest failure on Windows
      Fix gc_allocator.h compilation by Clang
      Fix 'condition pred!=NULL is always true' compiler warning
      Eliminate 'possible loss of data' compiler warning in cordprnt (MS VC)
      Eliminate 'possible loss of data' compiler warning in disclaim_test (MS VC)
      Eliminate 'conversion from size_t to int' MSVC warning in subthread_create
      Eliminate 'conversion from size_t to int' MSVC warning in cordprnt.c
      Eliminate 'conversion from int to void*' MS VC warning in cordtest (x64)
      Workaround 'expression is only useful for its side effects' WCC warning
      Eliminate 'comparing signed and unsigned values' BCC warning in cordtest
      Eliminate 'conversion may lose significant digits' BCC warning in de_win
      Fix subexpression widening in memhash() of disclaim_weakmap_test
      Update ChangeLog file (v7.2 - v7.4 changes only)
      Update ChangeLog file (v7.6 changes)
      Update ChangeLog file (v8.0 changes)
      Fix a typo in GC_init comment
      Disable mprotect-based incremental GC if /proc roots are used (Linux)
      Prevent WARN of incompatible incremental GC if default or manual VDB
      Define OS_TYPE and DATAEND for UWP targets
      Refactoring of WoW64 workaround (Win32)
      Eliminate 'static GC_sysinfo definition has incomplete type' Clang warning
      Fix GC_new_hblk prototype in a comment
      Fix 'ACCESS_VIOLATION in marker' GC warning on Win32 async thread start
      Do not hold GC_fault_handler_lock when in Sleep (Win32)
      Update AUTHORS file
      Update ChangeLog file (v7.2 - v7.4 changes only)
      Update ChangeLog file (v7.6 changes)
      Update ChangeLog file (v8.0 changes)
      .gitignore: Collapse multiple lib*.so items in a single one
      Fix gc_cpp.h file name in comments after renaming
      Update AUTHORS file
      Remove a note in README.macros that work in progress
      Remove obsolete information in README.darwin
      Do not use iOS private symbols
      Compile C++ code with exception handling enabled in NT_MAKEFILE
      Update AUTHORS file (add John David Anglin)
      Update AUTHORS file (add Thomas Thiriez)
      Fix 'write to GC log failed' error (Cygwin)
      Fix abort in GC_printf when gctest is built as WinMain executable (Cygwin)
      New macro to avoid system-wide new/delete inlining in gc_cpp.h (Win32)
      AppVeyor CI: Test cygwin64 single-threaded build with -D USE_WINALLOC
      Eliminate 'gc_pthread_redirects.h should contain header guard' code defect
      Fix 'invalid token at start of a preprocessor expression' in misc.c
      Update ChangeLog file (v7.2 - v7.4 changes only)
      Update ChangeLog file (v7.6 changes)
      Update ChangeLog file (v8.0 changes)
      Travis CI: Set dist image to xenial
      Travis CI: Remove deprecated deploy skip_cleanup key
      Travis CI: Rename matrix key to jobs
      Travis CI: Rename language c++ key value to cpp
      Travis CI: Fix '-std=c11 is valid for C/ObjC but not for C++' warning
      Travis CI: Set default OS to Linux
      Travis CI: Change deploy api_key (deprecated) to edge
      Update AUTHORS file (add Jonas Hahnfeld)
      Workaround clang-3.8/s390x bug when processing __builtin_frame_address
      Update AUTHORS file
      Update AUTHORS file (add Nikita Ermakov)
      Update AUTHORS file (add Clement Chigot)
      Update AUTHORS file (add Tim Gates)
      Fix gc_cflags variable name in configure (HP/UX)
      Remove dead part of condition to define NEED_FIND_LIMIT in gc_priv.h
      Avoid gcc stringop-overflow warning for intended overflow in smashtest
      Fix 'GC_generic_malloc must be available' GCC error in new_gc_alloc.h
      Eliminate 'GC_non_gc_bytes is deprecated' warning in new_gc_alloc.h
      Eliminate 'cast between incompatible func types' warnings for FARPROC vars
      Eliminate 'implicit declaration of sbrk' gcc warning if -std=c11 on Cygwin
      Check _MSVC_LANG macro in addition to __cplusplus (MS VC)
      Fix misaligned tlfs passed to AO_load on m68k
      Update AUTHORS file (add Mahder Gebremedhin)
      Fix missing specific.c in CMake script
      Remove cord .h files from list of non-installed headers (Automake)
      Fix CMake build on macOS Catalina
      Fix 'Wrong __data_start/_end pair' if -Bsymbolic-functions used (Linux)
      Limit unmapped regions amount on DragonFly
      Fix data race regarding *rlh value in generic_malloc_many
      Fix 'scope of phdr can be reduced' cppcheck error in free_block_ending_at
      Update ChangeLog file (v7.2 - v7.4 changes only)
      Update ChangeLog file (v7.6 changes)
      Update ChangeLog file (v8.0 changes)
      Fix page_was_[ever_]dirty() for static roots (Solaris)
      Do not report 'Incremental GC incompatible' warning more than once
      Fix GC_proc_fd value in child process at fork (Solaris)
      Fix missing scratch_last_end_ptr update (Irix)
      Fix missing heap limits adjustment if scratch_recycle_inner is called
      Revert "Fix missing heap limits adjustment if scratch_recycle is called"
      Update ChangeLog file (v7.2 - v7.4 changes only)
      Update ChangeLog file (v7.6 changes)
      Update ChangeLog file (v8.0 changes)
      Fix missing GC_quiet declaration in pcr_interface.c
      Fix handling of areas smaller than page size in GC_scratch_recycle
      Fix assertion violation in register_dynlib_callback on Android
      Ensure process is running on one CPU core if AO ops are emulated with locks
      Fix overflow of scratch_free_ptr value
      Fix GC_with_callee_saves_pushed for Android NDK r23 (clang-12)
      Fix 'Wrong finalization data' gctest failure using noinline (MS VC x86)
      Update comment in add_to_heap about recompute of GC_collect_at_heapsize
      Update ChangeLog file (v7.2 - v7.4 changes only)
      Update ChangeLog file (v7.6 changes)
      Update ChangeLog file (set v7.2o release date)
      Update ChangeLog file (set v7.4.20 release date)
      Update ChangeLog file (v8.0 changes)
      [8.0.6]

Ivan R (1):
      Fix 'ISO C++17 does not allow dynamic exception spec' clang-8 error

Jasper Lievisse Adriaanse (2):
      Fix word size and alignment for OpenBSD/mips64(el)
      Use __data_start instead of _fdata on OpenBSD/mips64

John David Anglin (3):
      Fix mmap() failures on HP/UX
      Fix STACKBOTTOM on 32-bit HP/UX 11.11
      Use pstat_getprocvm to determine main stack bottom on HP-UX

Jonas Hahnfeld (1):
      Add threading libraries to bdw-gc.pc

Jonathan Chambers (2):
      Prevent GetThreadContext failure (Windows)
      Add loop to handle abort error like in suspend logic on Darwin

Kurt Miller (2):
      Fix GC_OPENBSD_THREADS definition (OpenBSD/hppa)
      Use HEURISTIC2 on OpenBSD when single-threaded

Mahder Gebremedhin (1):
      Fix missing gc_dlopen.c in CMake script

Massimiliano Gubinelli (1):
      Fix mmap(PROT_NONE) failed if memory unmapping is enabled (Haiku)

Nikita Ermakov (1):
      Fix 'undefined reference to __data_start' linker error on RISC-V

Peter Budai (1):
      Support MSYS builds in configure

Peter Wang (4):
      Fix 'ulong undefined' compilation error on AIX
      Fix mmap(PROT_NONE) failure on AIX
      Fix 'use of undeclared BUS_PAGE_FAULT' compilation error on FreeBSD 12
      Limit number of unmapped regions (Linux)

Sorawee Porncharoenwase (1):
      Fix a typo in 'primitives' word in ChangeLog

Thomas Thiriez (1):
      Allocate start_info struct on the stack in GC_pthread_create

Tim Gates (1):
      Fix a typo in msvc_dbg.c comment (machine)

Victor Romero (1):
      Fix build for OS X (CMake)