[update to 7.6.10] Guard against potential buffer overflow in CORD_next and CORD_pos_fetch
Demyan Kimitsa (1):
      Fix start_world not resuming all threads on Darwin

Fabrice Fontaine (1):
      Fix linkage with a system libatomic_ops shared library

Ivan Maidanski (48):
      Use include gc.h with the angle brackets in the man page synopsis
      Fix 'undefined reference to GC_incremental' linker error in pthread_start
      Fix delete operator redirection if gc_cpp is built as .dll (Cygwin, MinGW)
      Travis CI: Put GNU S/W download base URL in a dedicated variable
      Fix indentation of 'define GC_DATAEND' in gc.h
      Update AUTHORS file (add Demyan Kimitsa)
      Fix missing curses.h in cord/de when compiling manually (MS VC, MinGW)
      Fix GC_VSNPRINTF in cordprnt for DJGPP and MS VC for WinCE
      Fix comment typo in CMakeLists.txt
      Refine documentation in gc_disclaim.h
      Fix unneeded end_stubborn_change in disclaim_test
      Test marking of finalizer closure object in disclaim_test
      Fix concurrent bitmap update in GC_dirty
      Use AO_or in async_set_pht_entry_from_index if available
      Call real pthread_sigmask instead of its wrapper in start_mark_threads
      Fix memory allocation on GCF (Linux/x64)
      Update ChangeLog file (v7.2 - v7.4 changes only)
      Update ChangeLog file (v7.6 changes)
      .gitignore: Ignore disclaim_weakmap_test executable file
      Fix GC_register_disclaim_proc for leak-finding mode
      Fix hbp overflow in GC_install_counts
      Fix test_cpp assertion violation in find-leak mode
      Guard against potential buffer overflow in CORD_next and CORD_pos_fetch
      Update AUTHORS file
      Add paths to filenames mentioned in the copyright section in README
      Fix 'collecting from unknown thread' abort in leak-finding mode for Win32
      Fix 'too wide non-owner permissions are set for resource' code defect
      Update AUTHORS file (add Fabrice Fontaine)
      Fix tests linkage with internal atomic_ops.o
      Eliminate 'non-virtual destructor for class with inheritors' CSA warning
      Reduce scope of local variables in GC_remove_all_threads_but_me
      Eliminate 'casting signed to bigger unsigned int' CSA warning
      New macro to suppress printing of leaked objects
      Travis CI: Test with FIND_LEAK
      Travis CI: Execute cppcheck without sudo and -U long
      Travis CI: Use latest (1.85) release version of cppcheck
      Prevent double inclusion of javaxfc.h and private/specific.h
      Fix lock assertion violation in get_index if GC_ALWAYS_MULTITHREADED
      Fix 'set_pht_entry_from_index_concurrent value is unknown' cppcheck warning
      Fix a deadlock in write_fault_handler if AO_or is emulated
      Travis CI: Fix odr-violation reported by ASan when compiled as C++
      Refine HIDE_POINTER documentation for the case of the leak-finding mode
      Travis CI: Do not run cppcheck twice for cord, tests, tools source files
      Update ChangeLog file (v7.2 - v7.4 changes only)
      Update ChangeLog file (v7.6 changes)
      Update ChangeLog file (set v7.2m release date)
      Update ChangeLog file (set v7.4.16 release date)
      [7.6.10]

Max Mouratov (1):
      Fix comment typos in backgraph.c, de.c, gcconfig.h

Petter A. Urkedal (1):
      Fix marks and hb_n_marks consistency when disclaim returns true

Petter Urkedal (1):
      Fix marking of finalizer closure object

Wookey (1):
      Update documentation about arm64 ABI in gcconfig.h

== [7.6.10] 2018-12-13 ==

* Add paths to filenames mentioned in the copyright section in README
* Call real pthread_sigmask instead of its wrapper in start_mark_threads
* Eliminate 'casting signed to bigger unsigned int' CSA warning
* Eliminate 'non-virtual destructor for class with inheritors' CSA warning
* Fix 'collecting from unknown thread' abort in leak-finding mode for Win32
* Fix 'too wide non-owner permissions are set for resource' code defect
* Fix 'undefined reference to GC_incremental' linker error in pthread_start
* Fix GC_VSNPRINTF in cordprnt for DJGPP and MS VC for WinCE
* Fix GC_register_disclaim_proc for leak-finding mode
* Fix a deadlock in write_fault_handler if AO_or is emulated
* Fix comment typos in CMakeLists.txt, backgraph.c, de.c, gcconfig.h
* Fix concurrent bitmap update in GC_dirty
* Fix delete operator redirection if gc_cpp is built as .dll (Cygwin, MinGW)

(NEWS truncated at 15 lines)