gc: Autospec creation for update from version 7.6.4 to version 7.6.6
Calvin Hill (1):
      Initial support of Haiku/amd64 (back-port of commits 847927f, 2396ce1 from 'master')

Ivan Maidanski (40):
      Workaround 'address of auto-variable returned' cppcheck error (back-port of commit b51bdee1 from 'master')
      Update AUTHORS file (add Jay Krell)
      Fix arguments delimiter in pcr_interface.c (PCR)
      Fix man section number (3)
      Fix type of local variables receiving result of PHT_HASH (back-port of commit 037991eb from 'master')
      Update AUTHORS file (add Natanael Copa)
      Fix missing new-line in GC_INFOLOG_PRINTF call in ABORT_ARG<n>
      Fix dbg_mlc.c/o file name in documentation
      Fix typo in AIX macro name
      Travis CI: Output content of threadkey_test.log
      Remove API symbols renaming in WCC_MAKEFILE
      Fix include gc_gcj.h in thread_local_alloc.c (back-port of commit 60d9632a from 'master')
      Fix missing GC_generic_malloc_words_small implementation in new_gc_alloc.h
      Update ChangeLog file (v7.2 - v7.4 changes only) (a cherry-pick of commit 08a2e0ba from 'release-7_4')
      Update ChangeLog file (v7.6 changes only)
      Fix comment for debug_generic_malloc_inner[_ignore_off_page] (fix of commit 38965f279)
      Fix 'scope of var can be reduced' cppcheck err in enqueue_all_finalizers (back-port of commit b82af3a3 from 'master')
      Fix assertion violation in DllMain of win32_threads
      Fix thread_suspend fail for threads registered from key destructor (OS X)
      Explicitly unblock GC signals on GC initialization
      Eliminate 'there is pointer arithmetic with NULL' cppcheck warning
      Define GC_FREEBSD_THREADS and GC_ADD_CALLER macros for kFreeBSD (back-port of commit 5700d205 from 'master')
      Fix missing SIGBUS handler setup for kFreeBSD
      Fix null pointer dereference in get_private_path_and_zero_file (Symbian) (back-port of commit 9d019e2e from 'master')
      Fix null dereference in print_callers on backtrace_symbols failure
      Fix unbounded heap growth in case of intensive disappearing links usage (back-port of commits b04b346, 46e7ec2 from 'master')
      Eliminate TSan warning about data race when accessing GC_debugging_started
      Fix the collector hang when it is configured with --enable-gc-debug (back-port of commits d6ccabe, 2e8c66c from 'master')
      Update AUTHORS file (add Calvin Hill)
      Workaround Haiku pthread_join failure in subthreadcreate_test
      Workaround sem_wait failure in pthread_create on Haiku
      Support threads for DragonFly in configure (back-port of commit 19c81d80 from 'master')
      Fix data race during apply_to_each_object(reset_back_edge) (back-port of commit d7ea0b1 from 'master')
      Fix 'pointer of type void* used in arithmetic' compiler warning in dbg_mlc (fix of commit 8f63e5b)
      Update ChangeLog file (v7.2 - v7.4 changes only)
      Update ChangeLog file (add gc-7.4.12 release date)
      Workaround gctest hang on kFreeBSD if thread-local allocations are on (back-port of commit 228e9b2 from 'master')
      Eliminate 'boolean result used in bitwise operation' cppcheck warning
      Update ChangeLog file (v7.6 changes only)
      [7.6.6]

Jay Krell (1):
      Fix typo in comment in specific.h

Jonathan Chambers (1):
      Fix 'undefined reference to __builtin_unwind_init' linker error (ArmCC) (part of commit 9379c66 from Unity-Technologies/bdwgc)

Natanael Copa (1):
      Fix gctest with musl libc on s390x

== [7.6.6] 2018-04-20 ==

* Define GC_FREEBSD_THREADS and GC_ADD_CALLER macros for kFreeBSD
* Eliminate 'boolean result used in bitwise operation' cppcheck warning
* Eliminate 'there is pointer arithmetic with NULL' cppcheck warning
* Explicitly unblock GC signals on GC initialization
* Fix 'scope of var can be reduced' cppcheck err in enqueue_all_finalizers
* Fix 'undefined reference to __builtin_unwind_init' linker error (ArmCC)
* Fix arguments delimiter in pcr_interface.c (PCR)
* Fix assertion violation in DllMain of win32_threads
* Fix comment for debug_generic_malloc_inner[_ignore_off_page]
* Fix data race during apply_to_each_object(reset_back_edge)
* Fix dbg_mlc.c/o file name in documentation
* Fix gctest with musl libc on s390x
* Fix include gc_gcj.h in thread_local_alloc.c

(NEWS truncated at 15 lines)